# Generated by Django 3.2.7 on 2021-10-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
